minor tweaks

diff --git a/bin/nodes-apt-get b/bin/nodes-apt-get
--- a/bin/nodes-apt-get
+++ b/bin/nodes-apt-get
@@ -8,6 +8,21 @@ if [ "`id -un`" != "infinity" ]; then
    exit 1
 fi 
 
+set -o pipefail
+klist -s
+if [ $? -ne 0 ]; then
+   echo ">> ERROR: Valid TGT kerberos ticket is required!"
+   echo ""
+   exit 1
+fi 
+
+klist | grep "`id -un`@META" &> /dev/null
+if [ $? -ne 0 ]; then
+   echo ">> ERROR: Valid TGT kerberos ticket for `id -un`@META is required!"
+   echo ""
+   exit 1
+fi 
+
 EXTRA=""
 MODE="par"
 RUSER=root
@@ -36,14 +51,9 @@ while [ $# -gt 0 ]; do
             shift
             MODE="seq"
             ;;
-        '--user' | '-u' )
-            shift
-            RUSER=$1
-            shift
-            ;;
         '--help' | '-h' )
             shift
-            echo "nodes-apt-get [--sequential|-1] [--keep|-k] [--property|-p PROPERTY] [--group|-g GROUP] [--search|-s SEXP] [--user|-u USER] [--help|-h] [--] ARGS"
+            echo "nodes-apt-get [--sequential|-1] [--keep|-k] [--property|-p PROPERTY] [--group|-g GROUP] [--search|-s SEXP] [--help|-h] [--] ARGS"
             echo ""
             exit 0
             ;;
diff --git a/bin/nodes-run-cmd b/bin/nodes-run-cmd
--- a/bin/nodes-run-cmd
+++ b/bin/nodes-run-cmd
@@ -8,6 +8,21 @@ if [ "`id -un`" != "infinity" ]; then
    exit 1
 fi 
 
+set -o pipefail
+klist -s
+if [ $? -ne 0 ]; then
+   echo ">> ERROR: Valid TGT kerberos ticket is required!"
+   echo ""
+   exit 1
+fi 
+
+klist | grep "`id -un`@META" &> /dev/null
+if [ $? -ne 0 ]; then
+   echo ">> ERROR: Valid TGT kerberos ticket for `id -un`@META is required!"
+   echo ""
+   exit 1
+fi 
+
 EXTRA=""
 MODE="par"
 RUSER=root
@@ -56,6 +71,13 @@ while [ $# -gt 0 ]; do
             ;;
     esac
 done
+
+id "$RUSER" &> /dev/null
+if [ $? -ne 0 ]; then
+   echo ">> ERROR: Remote user '$RUSER' does not exist on the local machine!"
+   echo ""
+   exit 1
+fi 
 
 # get all nodes from torque
 NODES=`eval "pnodes --hosts $EXTRA"`
